# Generated by Django 2.2.14 on 2021-02-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('ban_giao', models.CharField(max_length=255)),
                ('loai_hinh', models.CharField(max_length=255)),
                ('quy_mo', models.CharField(max_length=255)),
                ('so_tang', models.CharField(max_length=255)),
                ('dien_tich', models.CharField(max_length=255)),
                ('toa_do', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
