# Generated by Django 3.0.5 on 2021-03-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.CharField(max_length=255)),
                ('html', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
